# Generated by Django 4.2.24 on 2025-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
