# Generated by Django 4.2.24 on 2025-09-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_uploadeddocument_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='text_content',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='text_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='text_translated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.uploadeddocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
